### ISSUE TITLE
navbar dropdown not working on smaller window

### ISSUE THREAD

**Issue by Ian-OBrien-503** [Ian-OBrien-503/Ian-OBrien-503.github.io#1]
My navbar works fine when i am on full screen on a large enough monitor, but when the screen is smaller it makes the options on the right hand side of the navbar a dropdown that won't toggle/work.  
Tried making sure i am loading my CDN in correct order, any ideas?

this is in index.html
![screenshot from 2019-02-28 11-12-10](https://user-images.githubusercontent.com/28540586/53591836-d42ed080-3b49-11e9-8beb-dccd9582d1a8.png)
![screenshot from 2019-02-28 11-12-00](https://user-images.githubusercontent.com/28540586/53591837-d4c76700-3b49-11e9-83c3-f8cd07750549.png)

**Comment by caterinasworld** [comment]
If you open your console, you’ll see an error. You are not loading the bootstrap.js file.

**Comment by Ian-OBrien-503** [comment]
fixed, thank you!
